# Notebook Imports

In [1]:
import pandas as pd
import numpy as np

# Constants

In [87]:
TRAINING_DATA_FILE='SpamData/02_Training/train-data.txt'
TEST_DATA_FILE='SpamData/02_Training/test-data.txt'

TOKEN_SPAM_PROB_FILE='SpamData/03_Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE='SpamData/03_Testing/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE='SpamData/03_Testing/prob-all-tokens.txt'

TEST_FEATURE_MATRIX='SpamData/03_Testing/test-features.txt'
TEST_TARGET_FILE='SpamData/03_Testing/test-target.txt'

VOCAB_SIZE=2500

# Read and Load Features from .txt Files

In [6]:
sparse_train_data=np.loadtxt(TRAINING_DATA_FILE,delimiter=' ',dtype=int)

In [4]:
sparse_test_data=np.loadtxt(TEST_DATA_FILE,delimiter=' ',dtype=int)

In [7]:
sparse_train_data[:5]

array([[ 0,  2,  1,  1],
       [ 0,  3,  1,  2],
       [ 0,  4,  1,  1],
       [ 0,  7,  1,  3],
       [ 0, 11,  1,  1]])

In [8]:
sparse_test_data[:5]

array([[8, 2, 1, 1],
       [8, 3, 1, 4],
       [8, 4, 1, 2],
       [8, 5, 1, 1],
       [8, 6, 1, 2]])

In [9]:
sparse_train_data.shape[0]

258360

In [10]:
sparse_test_data.shape[0]

117628

In [13]:
np.unique(sparse_train_data[:,0]).shape[0]

4015

In [14]:
np.unique(sparse_test_data[:,0]).shape[0]

1724

In [15]:
column_names=['DOC_ID']+['CATEGORY']+list(range(0,VOCAB_SIZE))

In [16]:
index_names=np.unique(sparse_train_data[:,0])

In [17]:
index_names

array([   0,    1,    2, ..., 5791, 5794, 5795])

In [18]:
full_train_data=pd.DataFrame(index=index_names,columns=column_names)

In [23]:
full_train_data.fillna(value=0,inplace=True)
full_train_data.head()

DOC_ID  CATEGORY  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

   2494  2495  2496  2497  2498  2499  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 2502 columns]

# Create a Full-Matrix from a Sparse-Matrix

In [24]:
def make_full_matrix(sparse_matrix,nr_words,doc_idx=0,word_idx=1,cat_idx=2,freq_idx=3):
    column_names=['DOC_ID']+['CATEGORY']+list(range(0,VOCAB_SIZE))
    doc_id_names=np.unique(sparse_matrix[:,0])
    full_matrix=pd.DataFrame(index=doc_id_names,columns=column_names)
    full_matrix.fillna(value=0,inplace=True)
    
    for i in range(sparse_matrix.shape[0]):
        doc_nr=sparse_matrix[i][doc_idx]
        word_id=sparse_matrix[i][word_idx]
        label=sparse_matrix[i][cat_idx]
        occurence=sparse_matrix[i][freq_idx]
        full_matrix.at[doc_nr,'DOC_ID']=doc_nr
        full_matrix.at[doc_nr,'CATEGORY']=label
        full_matrix.at[doc_nr,word_id]=occurence
        
    full_matrix.set_index('DOC_ID',inplace=True)
    return full_matrix
    

In [25]:
%%time
full_train_data=make_full_matrix(sparse_train_data,VOCAB_SIZE)


Wall time: 8.01 s


In [26]:
full_train_data.head()

CATEGORY  0  1  2  3  4  5  6   7  8  ...  2490  2491  2492  2493  \
DOC_ID                                        ...                           
0              1  0  0  1  2  1  0  0   3  0  ...     0     0     0     0   
1              1  7  1  2  0  1  0  0   1  0  ...     0     0     0     0   
2              1  6  1  1  0  1  0  0   1  0  ...     0     0     0     0   
3              1  6  0  0  2  4  0  3  13  0  ...     0     0     0     0   
4              1  5  1  2  0  1  0  0   1  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
0          0     0     0     0     0     0  
1          0     0     0     0     0     0  
2          0     0     0     0     0     0  
3          0     0     0     0     0     0  
4          0     0     0     0     0     0  

[5 rows x 2501 columns]

In [27]:
full_train_data.tail()

CATEGORY  0  1  2  3  4  5  6  7  8  ...  2490  2491  2492  2493  \
DOC_ID                                       ...                           
5789           0  3  1  0  1  0  0  0  1  0  ...     0     0     0     0   
5790           0  1  1  1  0  0  0  1  0  0  ...     0     0     0     0   
5791           0  3  1  0  1  1  0  0  0  1  ...     0     0     0     0   
5794           0  1  1  1  0  0  1  2  0  0  ...     0     0     0     0   
5795           0  3  4  2  0  5  0  3  0  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
5789       0     0     0     0     0     0  
5790       0     0     0     0     0     0  
5791       0     0     0     0     0     0  
5794       0     0     0     0     0     0  
5795       0     0     0     0     0     0  

[5 rows x 2501 columns]

# Training the naive bayes model

## Finding Probability of Spam

In [39]:
full_train_data[full_train_data.CATEGORY==1].shape[0]

1250

In [63]:
full_train_data[full_train_data.CATEGORY==0].shape[0]

2765

In [41]:
full_train_data.shape[0]

4015

In [42]:
prob_spam=full_train_data[full_train_data.CATEGORY==1].shape[0]/full_train_data.shape[0]

In [43]:
prob_spam

0.31133250311332505

## Total Number of Words

In [44]:
full_train_features=full_train_data.loc[:,full_train_data.columns != 'CATEGORY']
full_train_features.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          0     0     1     2     1     0     0     3     0     0  ...     0   
1          7     1     2     0     1     0     0     1     0     0  ...     0   
2          6     1     1     0     1     0     0     1     0     0  ...     0   
3          6     0     0     2     4     0     3    13     0     0  ...     0   
4          5     1     2     0     1     0     0     1     0     0  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [46]:
email_lengths=full_train_features.sum(axis=1)
email_lengths.shape

(4015,)

In [47]:
total_wc=email_lengths.sum()

In [48]:
total_wc

430996

## Number of Tokens in Spam Emails

In [51]:
spam_train_features=full_train_data.loc[full_train_data.CATEGORY == 1,full_train_data.columns != 'CATEGORY']
spam_train_features.shape

(1250, 2500)

In [52]:
spam_lengths=spam_train_features.sum(axis=1)
spam_lengths.shape

(1250,)

In [64]:
spam_wc=spam_lengths.sum()

In [65]:
spam_wc

178591

In [59]:
ham_train_features=full_train_data.loc[full_train_data.CATEGORY == 0,full_train_data.columns != 'CATEGORY']
ham_train_features.shape

(2765, 2500)

In [60]:
ham_lengths=ham_train_features.sum(axis=1)
ham_lengths.shape

(2765,)

In [66]:
nonspam_wc=ham_lengths.sum()

In [67]:
nonspam_wc

252405

## Summing the tokens occuring in Spam

In [68]:
full_train_features.shape

(4015, 2500)

In [69]:
train_spam_tokens=full_train_features.loc[full_train_data.CATEGORY==1]

In [72]:
train_spam_tokens.shape

(1250, 2500)

In [73]:
summed_spam_tokens=train_spam_tokens.sum(axis=0) + 1
summed_spam_tokens.shape

(2500,)

## Summing the tokens occuring in Ham

In [74]:
train_ham_tokens=full_train_features.loc[full_train_data.CATEGORY==0]
summed_ham_tokens=train_ham_tokens.sum(axis=0) + 1
summed_ham_tokens.shape

(2500,)

In [75]:
summed_ham_tokens.tail()

2495    38
2496    32
2497    30
2498    33
2499    20
dtype: int64

# P(Token | Spam)

In [76]:
prob_tokens_spam=summed_spam_tokens/(spam_wc+VOCAB_SIZE)
prob_tokens_spam[:5]

0    0.012022
1    0.005169
2    0.006737
3    0.011188
4    0.006687
dtype: float64

In [77]:
prob_tokens_spam.sum()

0.9999999999999999

# P(Token | Ham)


In [80]:
prob_tokens_nonspam=summed_ham_tokens/(nonspam_wc+VOCAB_SIZE)
prob_tokens_nonspam[:5]

0    0.021510
1    0.010153
2    0.008019
3    0.003680
4    0.006320
dtype: float64

In [81]:
prob_tokens_nonspam.sum()

1.0

# P(Token)

In [82]:
prob_tokens_all=full_train_features.sum(axis=0)/total_wc

In [83]:
prob_tokens_all.sum()

0.9999999999999999

# Save the Trained Model

In [86]:
np.savetxt(TOKEN_SPAM_PROB_FILE,prob_tokens_spam)
np.savetxt(TOKEN_HAM_PROB_FILE,prob_tokens_nonspam)
np.savetxt(TOKEN_ALL_PROB_FILE,prob_tokens_all)

# Prepare Test Data

In [88]:
sparse_test_data.shape

(117628, 4)

In [89]:
%%time
full_test_data=make_full_matrix(sparse_test_data,VOCAB_SIZE)

Wall time: 4.42 s


In [90]:
X_test=full_test_data.loc[:,full_test_data.columns != 'CATEGORY']
y_test=full_test_data.CATEGORY

In [91]:
np.savetxt(TEST_TARGET_FILE,y_test)
np.savetxt(TEST_FEATURE_MATRIX,X_test)